### PR TITLE
Set GOPROXY env variable for Athens

### PR DESCRIPTION
**Pull request by bnrjee**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by bnrjee** [comment]
Creating a prow setup. Will upload test results.

**Comment by micahhausler** [comment]
/hold

@bnrjee just comment with`/unhold` when you want to merge

**Review by micahhausler — APPROVED** [review]

**Comment by bnrjee** [comment]
Will retest one of the existing job. Merging this PR.
/unhold

**Pull request merged**
